import { Product, Translation } from './types';

export const TRANSLATIONS: Record<'en' | 'bn', Translation> = {
  en: {
    dashboard: 'Dashboard',
    pos: 'Point of Sale',
    inventory: 'Inventory',
    settings: 'Settings',
    expenses: 'Expenses',
    totalSales: 'Total Sales',
    netProfit: 'Net Profit',
    totalOrders: 'Total Orders',
    totalExpenses: 'Total Expenses',
    lowStock: 'Low Stock',
    addToCart: 'Add',
    searchPlaceholder: 'Search product...',
    checkout: 'Checkout',
    print: 'Print Receipt',
    close: 'Close',
    invoiceTitle: 'Money Receipt',
    item: 'Item',
    qty: 'Qty',
    price: 'Price',
    total: 'Total',
    thankYou: 'Thank you for shopping with us!',
    stockLevel: 'Stock',
    cost: 'Cost',
    actions: 'Actions',
    addProduct: 'Add Product',
    addExpense: 'Add Expense',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Delete this item?',
    unit: 'Unit',
    customerName: 'Customer Name',
    customerPhone: 'Mobile Number',
    paidAmount: 'Paid Amount',
    dueAmount: 'Due / Rest',
    changeAmount: 'Change / Return',
    totalDue: 'Total Due',
    dueList: 'Due List',
    date: 'Date',
    purchasedItems: 'Purchased Items',
    noDueFound: 'No unpaid records found.',
    view: 'View',
    login: 'Login',
    register: 'Register Store',
    storeName: 'Store Name',
    username: 'Username',
    pin: 'Security PIN',
    logout: 'Logout',
    downloadReport: 'Download Monthly Report',
    description: 'Description',
    amount: 'Amount',
    profile: 'Store Profile',
    storeAddress: 'Store Address',
    storePhone: 'Store Phone',
    updateProfile: 'Update Profile',
    profileUpdated: 'Profile updated successfully!',
    download: 'Download',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    pos: 'বিক্রয় কেন্দ্র',
    inventory: 'মজুদ পণ্য',
    settings: 'সেটিংস',
    expenses: 'খরচ / ব্যয়',
    totalSales: 'মোট বিক্রয়',
    netProfit: 'নিট লাভ',
    totalOrders: 'মোট অর্ডার',
    totalExpenses: 'মোট খরচ',
    lowStock: 'স্বল্প মজুদ',
    addToCart: 'যোগ করুন',
    searchPlaceholder: 'পণ্য খুঁজুন...',
    checkout: 'চেকআউট',
    print: 'রশিদ প্রিন্ট',
    close: 'বন্ধ করুন',
    invoiceTitle: 'ক্রয় রশিদ',
    item: 'পণ্য',
    qty: 'পরিমাণ',
    price: 'দাম',
    total: 'মোট',
    thankYou: 'আমাদের সাথে থাকার জন্য ধন্যবাদ!',
    stockLevel: 'মজুদ',
    cost: 'ক্রয় মূল্য',
    actions: 'অ্যাকশন',
    addProduct: 'পণ্য যোগ',
    addExpense: 'খরচ যোগ করুন',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    confirmDelete: 'আপনি কি মুছে ফেলতে চান?',
    unit: 'একক',
    customerName: 'ক্রেতার নাম',
    customerPhone: 'মোবাইল নম্বর',
    paidAmount: 'জমা দেওয়া হয়েছে',
    dueAmount: 'বাকি / ডিউ',
    changeAmount: 'ফেরত',
    totalDue: 'মোট বাকি',
    dueList: 'বাকি খাতা',
    date: 'তারিখ',
    purchasedItems: 'ক্রীত পণ্য',
    noDueFound: 'কোনো বকেয়া পাওয়া যায়নি।',
    view: 'দেখুন',
    login: 'লগ ইন',
    register: 'দোকান রেজিস্ট্রেশন',
    storeName: 'দোকানের নাম',
    username: 'ব্যবহারকারীর নাম',
    pin: 'পিন নম্বর',
    logout: 'লগ আউট',
    downloadReport: 'মাসিক রিপোর্ট ডাউনলোড',
    description: 'বিবরণ',
    amount: 'টাকার পরিমাণ',
    profile: 'দোকানের তথ্য',
    storeAddress: 'দোকানের ঠিকানা',
    storePhone: 'দোকানের ফোন',
    updateProfile: 'তথ্য আপডেট করুন',
    profileUpdated: 'তথ্য সফলভাবে আপডেট হয়েছে!',
    download: 'ডাউনলোড',
  }
};

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Basmati Rice (5kg)',
    nameBn: 'বাসমতি চাল (৫ কেজি)',
    price: 1200,
    cost: 1000,
    category: 'Grocery',
    stock: 50,
    unit: 'kg',
    image: 'https://picsum.photos/200/200?random=1'
  },
  {
    id: '2',
    name: 'Soybean Oil (1L)',
    nameBn: 'সয়াবিন তেল (১ লিটার)',
    price: 180,
    cost: 165,
    category: 'Grocery',
    stock: 100,
    unit: 'L',
    image: 'https://picsum.photos/200/200?random=2'
  },
  {
    id: '3',
    name: 'Milk (1L)',
    nameBn: 'দুধ (১ লিটার)',
    price: 90,
    cost: 80,
    category: 'Dairy',
    stock: 20,
    unit: 'L',
    image: 'https://picsum.photos/200/200?random=3'
  },
  {
    id: '4',
    name: 'Premium Tea',
    nameBn: 'প্রিমিয়াম চা',
    price: 450,
    cost: 380,
    category: 'Beverage',
    stock: 4, // Low stock simulation
    unit: 'box',
    image: 'https://picsum.photos/200/200?random=4'
  },
  {
    id: '5',
    name: 'Detergent Powder',
    nameBn: 'ডিটারজেন্ট পাউডার',
    price: 320,
    cost: 250,
    category: 'Household',
    stock: 60,
    unit: 'pkt',
    image: 'https://picsum.photos/200/200?random=5'
  },
   {
    id: '6',
    name: 'Biscuits Pack',
    nameBn: 'বিস্কুট প্যাকেট',
    price: 50,
    cost: 35,
    category: 'Snacks',
    stock: 150,
    unit: 'pkt',
    image: 'https://picsum.photos/200/200?random=6'
  }
];